import {
  AfterViewInit,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  computed,
  ElementRef,
  inject,
  type OnDestroy,
  signal,
} from '@angular/core';
import { WorkspaceService } from 'svg-engine/edit';
import { ViewportService } from 'svg-engine/render';

/** A single ruler tick — generated by the layout-aware computation below. */
interface Tick {
  readonly key: string;
  /** Absolute CSS px from the ruler's container origin (NOT a percent). */
  readonly positionPx: number;
  readonly major: boolean;
  readonly label: string;
}

/** Ruler bar thickness (left + top). Mirrored in CSS via `.ruler-h` / `.ruler-v`. */
const RULER_THICKNESS_PX = 24;

/**
 * Top + left rulers showing document-space coordinates.
 *
 * **Layout-accurate (Fase 6 UX polish)**: tick positions are computed
 * from the inner SVG's actual screen rectangle via
 * `SVGSVGElement.getScreenCTM()`, NOT from a naive percent-of-ruler
 * calculation. This is the difference that makes rulers line up with
 * the page rect even when the SVG content is letterboxed inside its
 * container.
 *
 * **Why getScreenCTM and not percent**:
 * Default SVGs use `preserveAspectRatio="xMidYMid meet"` — the
 * content scales by the SMALLER axis to fit, then centers in the
 * other axis with letterbox padding. A "percent across ruler" tick
 * computation assumes the SVG fills the ruler bar exactly with no
 * padding; when there's letterbox, the tick at "doc x = 0" ends up
 * `letterbox_px` to the left of the actual SVG content's `x=0` edge.
 * Users see a ruler 0 that doesn't line up with their page corner —
 * exactly the bug reported during Fase 6 UX polish.
 *
 * `getScreenCTM` gives the live transformation from SVG user-space
 * to screen px, so for any doc value `V` we can ask "where is V on
 * screen right now?" and place the tick at the right absolute CSS
 * pixel. Works regardless of preserveAspectRatio mode, CSS transforms
 * on ancestors, or even multi-axis CSS zoom.
 *
 * **Reactivity**: ticks re-compute when (a) the viewport viewBox
 * changes (pan/zoom), or (b) the SVG element / ruler host resize
 * (ResizeObserver bumps a `layoutVersion` signal that's read inside
 * the computed). Both paths trigger CD via OnPush.
 *
 * **SSR / jsdom fallback**: when no SVG is reachable or `getScreenCTM`
 * is missing, falls back to the prior percent-based approach so the
 * component remains constructible and tests don't crash.
 */
@Component({
  selector: 'svge-rulers',
  standalone: true,
  template: `
    @if (visible()) {
      <div class="ruler ruler-h" aria-hidden="true">
        @for (t of horizontalTicks(); track t.key) {
          <div
            class="tick"
            [class.major]="t.major"
            [style.left.px]="t.positionPx"
            [attr.data-label]="t.major ? t.label : null"
          ></div>
        }
        @if (cursorIndicatorH(); as ind) {
          <div class="cursor-indicator h" [style.left.px]="ind.positionPx" aria-hidden="true"></div>
        }
      </div>
      <div class="ruler ruler-v" aria-hidden="true">
        @for (t of verticalTicks(); track t.key) {
          <div
            class="tick"
            [class.major]="t.major"
            [style.top.px]="t.positionPx"
            [attr.data-label]="t.major ? t.label : null"
          ></div>
        }
        @if (cursorIndicatorV(); as ind) {
          <div class="cursor-indicator v" [style.top.px]="ind.positionPx" aria-hidden="true"></div>
        }
      </div>
      <div class="corner" aria-hidden="true"></div>
    }
  `,
  styles: `
    :host {
      display: block;
      position: relative;
      width: 100%;
      height: 100%;
      pointer-events: none;
      font-family: ui-monospace, monospace;
      font-size: 10px;
      line-height: 12px;
      color: var(--mat-sys-on-surface, #222);
    }
    .ruler {
      position: absolute;
      background: var(--mat-sys-surface-container-low, #f5f5f5);
      border: 1px solid var(--mat-sys-outline-variant, #ddd);
    }
    .ruler-h {
      top: 0;
      left: 24px;
      right: 0;
      height: 24px;
      border-left: 0;
      overflow: hidden;
    }
    .ruler-v {
      top: 24px;
      left: 0;
      bottom: 0;
      width: 24px;
      border-top: 0;
      overflow: hidden;
    }
    .corner {
      position: absolute;
      top: 0;
      left: 0;
      width: 24px;
      height: 24px;
      background: var(--mat-sys-surface-container, #eee);
      border-right: 1px solid var(--mat-sys-outline-variant, #ddd);
      border-bottom: 1px solid var(--mat-sys-outline-variant, #ddd);
    }
    .tick {
      position: absolute;
    }
    .ruler-h .tick {
      bottom: 0;
      width: 0;
      height: 6px;
      border-left: 1px solid var(--mat-sys-outline-variant, #bbb);
    }
    .ruler-h .tick.major {
      height: 12px;
      border-left-color: var(--mat-sys-on-surface-variant, #777);
    }
    .ruler-h .tick.major[data-label]::after {
      content: attr(data-label);
      position: absolute;
      top: -12px;
      left: 2px;
      white-space: nowrap;
      color: var(--mat-sys-on-surface, #333);
    }
    .ruler-v .tick {
      right: 0;
      width: 6px;
      height: 0;
      border-top: 1px solid var(--mat-sys-outline-variant, #bbb);
    }
    .ruler-v .tick.major {
      width: 12px;
      border-top-color: var(--mat-sys-on-surface-variant, #777);
    }
    .ruler-v .tick.major[data-label]::after {
      content: attr(data-label);
      position: absolute;
      top: 2px;
      left: -10px;
      white-space: nowrap;
      writing-mode: vertical-rl;
      transform: rotate(180deg);
      color: var(--mat-sys-on-surface, #333);
    }
    /* Cursor-position indicator — small filled triangle pointing into
       the canvas, following the mouse along each ruler bar. Convention
       from Affinity / Illustrator / Photoshop: a single triangle per
       axis (no label, no full-bar line) — minimal visual weight, clear
       reference. Color is derived from the system primary so it sits
       above tick marks in z-order and stays legible across themes. */
    .cursor-indicator {
      position: absolute;
      width: 8px;
      height: 8px;
      background: var(--mat-sys-primary, #1976d2);
      pointer-events: none;
      /* Slightly above 1 so it visually crosses major tick caps. */
      z-index: 2;
    }
    /* Horizontal ruler: triangle pointing down, anchored to bar bottom,
       centered on the cursor X. CSS triangles via clip-path keep the
       markup tiny (no SVG nodes per frame). */
    .cursor-indicator.h {
      bottom: 0;
      transform: translateX(-50%);
      clip-path: polygon(0 0, 100% 0, 50% 100%);
    }
    /* Vertical ruler: triangle pointing right, anchored to bar right
       edge, centered on the cursor Y. */
    .cursor-indicator.v {
      right: 0;
      transform: translateY(-50%);
      clip-path: polygon(0 0, 100% 50%, 0 100%);
    }
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SvgeRulers implements AfterViewInit, OnDestroy {
  private readonly host = inject(ElementRef<HTMLElement>);
  private readonly cdr = inject(ChangeDetectorRef);
  private readonly ws = inject(WorkspaceService);
  private readonly viewport = inject(ViewportService);

  protected readonly visible = computed(() => this.ws.rulers().enabled);

  /**
   * Manually-bumped signal that re-fires whenever ResizeObserver detects
   * the SVG or the host changing size. The ticks `computed()` reads it,
   * so a resize triggers a tick recomputation + CD without needing
   * a stale-time-based polling loop.
   */
  private readonly layoutVersion = signal(0);
  private svgRef: SVGSVGElement | null = null;
  private resizeObserver: ResizeObserver | null = null;

  ngAfterViewInit(): void {
    // The rulers are mounted as a SIBLING of the canvas-inner div that
    // contains the renderer's <svg>. Walk the parent to find it.
    const parent = this.host.nativeElement.parentElement;
    if (parent === null) return;
    const svg = parent.querySelector('svg');
    if (svg !== null) {
      this.svgRef = svg as SVGSVGElement;
    }
    if (typeof ResizeObserver !== 'undefined') {
      this.resizeObserver = new ResizeObserver(() => {
        // Bump the signal to invalidate the ticks computed. CD is
        // triggered automatically via signal reactivity in OnPush
        // components — no markForCheck needed.
        this.layoutVersion.update((v) => v + 1);
      });
      if (this.svgRef !== null) this.resizeObserver.observe(this.svgRef);
      this.resizeObserver.observe(this.host.nativeElement);
    }
    // Initial bump so the first frame after view-init recomputes
    // ticks with the now-available SVG ref.
    this.layoutVersion.update((v) => v + 1);
    this.cdr.markForCheck();
  }

  ngOnDestroy(): void {
    this.resizeObserver?.disconnect();
    this.resizeObserver = null;
  }

  protected readonly horizontalTicks = computed<readonly Tick[]>(() => this.computeTicks('x'));
  protected readonly verticalTicks = computed<readonly Tick[]>(() => this.computeTicks('y'));

  /**
   * Cursor-position indicator for each ruler. Computed from the live
   * `ws.rulerCursor` signal (doc coords) projected to ruler-local CSS
   * pixels via the same CTM the ticks use. Returns `null` when:
   * - the pointer is outside the canvas (signal is null)
   * - the CTM isn't available (jsdom / SSR — indicator hidden)
   * - the projected position falls outside the ruler bar (avoids the
   *   indicator floating in the corner square or below the bar end)
   *
   * Per-axis computeds (instead of one for both) so that horizontal
   * panning doesn't recompute the vertical indicator and vice versa.
   */
  protected readonly cursorIndicatorH = computed<{ positionPx: number } | null>(() =>
    this.computeCursorIndicator('x'),
  );
  protected readonly cursorIndicatorV = computed<{ positionPx: number } | null>(() =>
    this.computeCursorIndicator('y'),
  );

  private computeCursorIndicator(axis: 'x' | 'y'): { positionPx: number } | null {
    // Touch reactive deps so the computed re-fires on layout / viewport
    // change in addition to cursor moves.
    this.layoutVersion();
    this.viewport.viewBox();
    const cursor = this.ws.rulerCursor();
    if (cursor === null) return null;
    const ctmInfo = this.computeCtmInfo(axis);
    if (ctmInfo === null) return null;
    const value = axis === 'x' ? cursor.x : cursor.y;
    if (!Number.isFinite(value)) return null;
    const positionPx = ctmInfo.docOriginScreenPx + value * ctmInfo.scale - ctmInfo.barStartPx;
    // Clamp to a 1-px tolerance on both ends so cursors *exactly* at
    // the edge still render, but cursors clearly off the bar are
    // hidden (prevents the indicator from drawing inside the corner
    // square or past the ruler's overflow:hidden boundary).
    if (positionPx < -0.5 || positionPx > ctmInfo.barLength + 0.5) return null;
    return { positionPx };
  }

  /**
   * Build the tick array for one axis.
   *
   * **Range covered**: ticks span the ENTIRE ruler bar, not just the
   * SVG content's visible viewBox. When the SVG is letterboxed inside
   * its container, the bar areas outside the SVG content (where the
   * checkerboard pasteboard shows) still get ticks — they represent
   * doc coordinates accessible via pan, so showing them is correct
   * (matches Illustrator / Affinity convention). The tick spacing is
   * derived from the full bar's doc-coord span so it scales naturally
   * with zoom.
   *
   * Uses `getScreenCTM` for layout-accurate positioning when available;
   * falls back to a viewBox-percent approximation for jsdom / SSR.
   */
  private computeTicks(axis: 'x' | 'y'): readonly Tick[] {
    // Touch both reactive dependencies up-front so the computed re-runs
    // when either changes.
    this.layoutVersion();
    const vb = this.viewport.viewBox();
    const vbStart = axis === 'x' ? vb.x : vb.y;
    const vbSpan = axis === 'x' ? vb.width : vb.height;
    if (vbSpan <= 0 || !Number.isFinite(vbSpan)) return [];

    // Try the layout-accurate path first.
    const ctmInfo = this.computeCtmInfo(axis);
    if (ctmInfo !== null) {
      // Doc-coord values at the bar's start (position 0) and end
      // (position barLength). Derived by inverting the projection
      //   positionPx = docOriginScreenPx + value * scale - barStartPx
      // to solve for `value` at the two boundary positions. This is
      // the KEY to filling the bar's letterbox edges with ticks —
      // the bar's doc-coord range is WIDER than the SVG viewBox when
      // there's letterboxing.
      const docAtBar0 = (ctmInfo.barStartPx - ctmInfo.docOriginScreenPx) / ctmInfo.scale;
      const docAtBarEnd =
        (ctmInfo.barStartPx + ctmInfo.barLength - ctmInfo.docOriginScreenPx) / ctmInfo.scale;
      const lo = Math.min(docAtBar0, docAtBarEnd);
      const hi = Math.max(docAtBar0, docAtBarEnd);
      const fullSpan = hi - lo;
      if (fullSpan <= 0 || !Number.isFinite(fullSpan)) return [];

      const targetMajors = 8;
      const rawStep = fullSpan / targetMajors;
      const major = niceTickSpacing(rawStep);
      const minor = major / 5;
      const firstMinor = Math.ceil(lo / minor);
      const lastMinor = Math.floor(hi / minor);

      const out: Tick[] = [];
      for (let i = firstMinor; i <= lastMinor; i++) {
        const value = i * minor;
        const positionPx = ctmInfo.docOriginScreenPx + value * ctmInfo.scale - ctmInfo.barStartPx;
        if (positionPx < 0 || positionPx > ctmInfo.barLength) continue;
        const isMajor = i % 5 === 0;
        out.push({
          key: `t${i}`,
          positionPx,
          major: isMajor,
          label: isMajor ? formatLabel(value) : '',
        });
      }
      return out;
    }

    // Fallback: percent-based positioning relative to ruler-bar length.
    // Used in jsdom / SSR where getScreenCTM is unavailable. Doesn't
    // extend into letterbox areas — but since those don't exist when
    // SVG fills its container 1:1 (the typical test scenario), this is
    // correct for the fallback case.
    const targetMajors = 8;
    const rawStep = vbSpan / targetMajors;
    const major = niceTickSpacing(rawStep);
    const minor = major / 5;
    const firstMinor = Math.ceil(vbStart / minor);
    const lastMinor = Math.floor((vbStart + vbSpan) / minor);

    const hostRect = this.host.nativeElement.getBoundingClientRect();
    const barLength = (axis === 'x' ? hostRect.width : hostRect.height) - RULER_THICKNESS_PX;
    if (barLength <= 0) return [];
    const out: Tick[] = [];
    for (let i = firstMinor; i <= lastMinor; i++) {
      const value = i * minor;
      const positionPx = ((value - vbStart) / vbSpan) * barLength;
      if (positionPx < 0 || positionPx > barLength) continue;
      const isMajor = i % 5 === 0;
      out.push({
        key: `t${i}`,
        positionPx,
        major: isMajor,
        label: isMajor ? formatLabel(value) : '',
      });
    }
    return out;
  }

  /**
   * Resolve the CTM-derived info needed to project doc coords to screen
   * px relative to the ruler bar. Returns null when the SVG isn't
   * reachable or getScreenCTM isn't available (jsdom, SSR).
   *
   * Math:
   * - `scale`: CSS px per doc unit on this axis (read from the CTM)
   * - `docOriginScreenPx`: absolute screen px of doc point (0,0) on
   *   this axis (also from the CTM)
   * - `barStartPx`: absolute screen px where the ruler BAR (not the
   *   host) starts on this axis (offset by RULER_THICKNESS for the
   *   corner square)
   * - `barLength`: CSS px length of the bar's visible area
   *
   * Ticks land at `docOriginScreenPx + value * scale - barStartPx`.
   */
  private computeCtmInfo(axis: 'x' | 'y'): {
    docOriginScreenPx: number;
    scale: number;
    barStartPx: number;
    barLength: number;
  } | null {
    const svg = this.svgRef;
    if (svg === null) return null;
    if (typeof svg.getScreenCTM !== 'function') return null;
    const ctm = svg.getScreenCTM();
    if (ctm === null) return null;
    if (typeof svg.createSVGPoint !== 'function') return null;
    const hostRect = this.host.nativeElement.getBoundingClientRect();
    if (hostRect.width <= 0 || hostRect.height <= 0) return null;

    // Project doc (0,0) and doc (1,1) through the CTM. The delta gives
    // the per-unit screen scale; the origin gives the offset.
    const p0 = svg.createSVGPoint();
    p0.x = 0;
    p0.y = 0;
    const s0 = p0.matrixTransform(ctm);
    const p1 = svg.createSVGPoint();
    p1.x = 1;
    p1.y = 1;
    const s1 = p1.matrixTransform(ctm);

    const docOriginScreenPx = axis === 'x' ? s0.x : s0.y;
    const scale = axis === 'x' ? s1.x - s0.x : s1.y - s0.y;

    // The ruler BAR starts RULER_THICKNESS_PX after the host's origin
    // (the corner square sits in that gap). Ticks are positioned with
    // [style.left.px] / [style.top.px] inside the ruler bar div, so we
    // subtract the bar's start position to get the local coordinate.
    const hostStart = axis === 'x' ? hostRect.left : hostRect.top;
    const barStartPx = hostStart + RULER_THICKNESS_PX;
    const barLength = (axis === 'x' ? hostRect.width : hostRect.height) - RULER_THICKNESS_PX;

    if (barLength <= 0 || !Number.isFinite(scale) || scale === 0) return null;
    return { docOriginScreenPx, scale, barStartPx, barLength };
  }
}

/**
 * Compute a "nice" major tick spacing from a raw target step. Picks
 * from {1, 2, 5} × 10ⁿ — standard ruler / axis-tick heuristic shared
 * with Matplotlib, d3-scale, Photoshop.
 */
function niceTickSpacing(raw: number): number {
  if (raw <= 0 || !Number.isFinite(raw)) return 1;
  const exponent = Math.floor(Math.log10(raw));
  const magnitude = Math.pow(10, exponent);
  const normalized = raw / magnitude;
  let nice: number;
  if (normalized < 1.5) nice = 1;
  else if (normalized < 3.5) nice = 2;
  else if (normalized < 7.5) nice = 5;
  else nice = 10;
  return nice * magnitude;
}

function formatLabel(value: number): string {
  if (Math.abs(value) >= 1000) return `${Math.round(value)}`;
  if (Math.abs(value) >= 1 || value === 0) return `${Math.round(value * 100) / 100}`;
  return value.toFixed(2);
}
